<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOJDLWy7\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOJDLWy7/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerOJDLWy7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerOJDLWy7\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerOJDLWy7\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'OJDLWy7',
    'container.build_id' => '23dd952e',
    'container.build_time' => 1591803893,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOJDLWy7');
