<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNaJYBHP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNaJYBHP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNaJYBHP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNaJYBHP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNaJYBHP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NaJYBHP',
    'container.build_id' => 'a0572e65',
    'container.build_time' => 1591329685,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNaJYBHP');
